services:
  postgres:
    image: postgres:16-alpine
    container_name: mini-banking-postgres
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking -d banking"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: mini-banking-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/banking
      SPRING_DATASOURCE_USERNAME: banking
      SPRING_DATASOURCE_PASSWORD: banking
    ports:
      - "8080:8080"

volumes:
  postgres_data:
