spring.application.name=mini-banking
server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:banking}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:banking}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.initialization-fail-timeout=0

spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
